Add siwe store and improve error handling
deckardkrug/web3-stores pull request #8
Opened 2022-01-29 20:14 UTC by deckardkrug

- [x] Agree on store structure
- [x] Add call method on contract store
- [x] Custom natspec based error messages
- [x] Siwe store 
- [x] Update readme
- [x] Testing

2022-01-30 12:04 UTC, deckardkrug commented on src/lib/index.ts
> +export function createContractStore(address: Account, abi: ethers.ContractInterface) {
Might turn the derived store into a class to avoid creating a complex return type.

2022-01-30 12:06 UTC, deckardkrug commented on src/routes/index.svelte
> +	let float = createContractStore(contractAddress, erc20abi);
Since I want to avoid creating a complex type and maintaining it, I initialized the store here. Using a class instead of a function to create the store could solve this problem.

2022-01-30 12:12 UTC, deckardkrug commented on src/routes/index.svelte
> +			float.update((previous) => ({
Ideally, we would not call the methods directly, but instead create a call method in the store so that we don't have to add a try catch to handle transaction reverts outside of the store. However, I'm not sure how best to implement this.

One option would be to encode the method name and arguments and just pass them to a store method to create a normal transaction that we can then deploy. However, this would remove the need for the ethers.js contract instance.

2022-01-30 20:53 UTC, sebastinez requested changes
The `lib/index.ts` looks fine to me, I think we have to try in the examples to be as idiomatic Svelte as possible.

2022-01-30 20:53 UTC, sebastinez commented on src/routes/index.svelte
> -			disabled={!$providerStore.connected}
Okay I think this was just good UX, since if you don't have the provider connected you most certainly are going to get an error.

2022-01-30 20:53 UTC, sebastinez commented on src/routes/index.svelte
> +	let result: { [key: string]: undefined } = {};
Instead of having a result variable and filling it with the contract data, I would go a more Svelte idiomatic way and call the `async fn getContractData` in the markup like I had on line 83-91.

2022-01-30 20:53 UTC, sebastinez commented on src/routes/index.svelte
> +			loading = false;
By reverting this and use this function directly in the code, we can scrap the loading variable, the try and catch and make it more idiomatic, 
```
{#await getContractData()}
  <p>Loading..</p>
{:then [...variable]}
```

2022-01-30 20:53 UTC, sebastinez commented on src/routes/index.svelte
>  		{/if}
The same from above

2022-01-30 20:53 UTC, sebastinez commented on src/routes/index.svelte
> +	let float = createContractStore(contractAddress, erc20abi);
Yeah this looks nice, but by creating the contractStore here, it throws an error since it has no provider connected..
Eventually to avoid using complex types we can do `any` and add a comment to convert into a class?

2022-01-30 21:10 UTC, deckardkrug commented on src/routes/index.svelte
> -			disabled={!$providerStore.connected}
Right, I just removed it to see if the error message is displayed correctly.

2022-01-30 21:13 UTC, deckardkrug commented on src/routes/index.svelte
> +	let result: { [key: string]: undefined } = {};
The problem with this approach is that it is hard to showcase what happens to the contract store if you switch your account. This way I was able to use listen to the store and call `getContractData` after a state change:

https://github.com/deckardkrug/web3-stores/blob/7deb3e8cc34a0dbc55f52ef63a37accb6f9374aa/src/routes/index.svelte#L16-L18

2022-01-30 21:16 UTC, deckardkrug commented on src/routes/index.svelte
> +			loading = false;
I did this for the same reason as described above. However I am going to experiment more with your approach, to see if we can find a way to both showcase the power of the contract store while going a more Svelte idiomatic way.

2022-01-30 21:18 UTC, deckardkrug commented on src/routes/index.svelte
> +	let float = createContractStore(contractAddress, erc20abi);
That sounds good!

2022-01-30 21:24 UTC, deckardkrug commented on src/routes/index.svelte
> +	let result: { [key: string]: undefined } = {};
In the example I added the signer to showcase that the contract signer changes when the account changes.

2022-01-30 21:26 UTC, sebastinez commented on src/routes/index.svelte
> +	let result: { [key: string]: undefined } = {};
Okay I get you, but you should still be able to do it like this and have the reactivness of the store

```ts
  $: getContractData = async () => {
    return await Promise.all([
      $float.contract.signer.getAddress(),
      $float.contract.name(),
      $float.contract.address,
      $float.contract.decimals(),
      $float.contract.symbol(),
      $float.contract.totalSupply()
    ]);
  }
```

2022-02-19 01:45 UTC, sebastinez approved these changes
Nice addition with the contract call methods and the siwe store 👍

2022-02-19 02:18 UTC, merged